Currently Minimal integration test breaking probably due to assembly incompatibility
A new sort of dll hell where assemblies we barely care about
differ by a minor minor version.  Or maybe something completely different
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.IHttpResponseStreamWriterFactory' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.0.0,